export type GrowthFixture={id:string;slug:string;matchweek:number;kickoff:string;home:string;away:string;homeScore:number|null;awayScore:number|null;status:string;hero:boolean;myth:string};
export const fallbackFixtures:GrowthFixture[]=[
 {id:"mw1-ars-cov",slug:"arsenal-v-coventry-city",matchweek:1,kickoff:"2026-08-21T19:00:00.000Z",home:"Arsenal",away:"Coventry City",homeScore:null,awayScore:null,status:"SCHEDULED",hero:true,myth:"Two banners approach the field. Only one will command the gate."},
 {id:"mw1-hul-mun",slug:"hull-city-v-manchester-united",matchweek:1,kickoff:"2026-08-22T11:30:00.000Z",home:"Hull City",away:"Manchester United",homeScore:null,awayScore:null,status:"SCHEDULED",hero:false,myth:"The cavalry meet the old grenadiers at the edge of the kingdom."},
 {id:"mw1-eve-cry",slug:"everton-v-crystal-palace",matchweek:1,kickoff:"2026-08-22T14:00:00.000Z",home:"Everton",away:"Crystal Palace",homeScore:null,awayScore:null,status:"SCHEDULED",hero:false,myth:"The old guard brace as the fyrd assemble beyond the wall."},
 {id:"mw1-bre-tot",slug:"brentford-v-tottenham-hotspur",matchweek:1,kickoff:"2026-08-22T16:30:00.000Z",home:"Brentford",away:"Tottenham Hotspur",homeScore:null,awayScore:null,status:"SCHEDULED",hero:true,myth:"Drilled ranks face proud spears beneath the evening sky."},
 {id:"mw1-mci-bou",slug:"manchester-city-v-bournemouth",matchweek:1,kickoff:"2026-08-23T13:00:00.000Z",home:"Manchester City",away:"Bournemouth",homeScore:null,awayScore:null,status:"SCHEDULED",hero:true,myth:"A swift horde meets corsairs who strike without warning."},
 {id:"mw1-new-liv",slug:"newcastle-united-v-liverpool",matchweek:1,kickoff:"2026-08-23T15:30:00.000Z",home:"Newcastle United",away:"Liverpool",homeScore:null,awayScore:null,status:"SCHEDULED",hero:false,myth:"Northern raiders collide. The coast will hear the shields."},
 {id:"mw1-ful-che",slug:"fulham-v-chelsea",matchweek:1,kickoff:"2026-08-24T19:00:00.000Z",home:"Fulham",away:"Chelsea",homeScore:null,awayScore:null,status:"SCHEDULED",hero:false,myth:"Marines hold the crossing as the elite guard advance."}
];
export const mythResult=(home:string,away:string,hs:number,as:number)=>hs===as?`${home} and ${away} plant both banners at dusk. Neither falls; the field is shared.`:hs>as?`${home}'s raid lands. The line is breached and ${away}'s banner falls.`:`${away}'s final charge breaks the gate. ${home}'s banner falls.`;
const warriorFiles:Record<string,string>={"Arsenal":"arsenal.png","Aston Villa":"aston-villa.png","Bournemouth":"bournemouth.png","AFC Bournemouth":"bournemouth.png","Brentford":"brentford.png","Brighton":"brighton.png","Brighton & Hove Albion":"brighton.png","Chelsea":"chelsea.png","Coventry City":"coventry.png","Crystal Palace":"crystal-palace.png","Everton":"everton.png","Fulham":"fulham.png","Hull City":"hull.png","Ipswich Town":"ipswich.png","Leeds United":"leeds.png","Liverpool":"liverpool.png","Manchester City":"manchester-city.png","Manchester United":"manchester-united.png","Newcastle United":"newcastle.png","Nottingham Forest":"nottingham-forest.png","Sunderland":"sunderland.png","Tottenham Hotspur":"tottenham.png"};
export const warriorImage=(club:string)=>`/warriors/${warriorFiles[club.replace(/ FC$/,'')]||"arsenal.png"}`;
