<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::table('users',function(Blueprint $t){$t->string('username')->nullable()->unique();$t->string('country_code',3)->nullable();$t->string('city')->nullable();$t->string('war_faction')->nullable();$t->text('bio')->nullable();$t->integer('matchday_points')->default(0);$t->integer('current_streak')->default(0);$t->integer('best_streak')->default(0);$t->date('last_active_on')->nullable();});
 Schema::create('user_badges',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('badge');$t->string('label');$t->timestamp('awarded_at');$t->unique(['user_id','badge']);});
 Schema::create('match_stories',function(Blueprint $t){$t->id();$t->foreignId('match_id')->unique()->constrained('matches')->cascadeOnDelete();$t->string('headline');$t->text('story');$t->json('beats')->nullable();$t->timestamp('generated_at');$t->timestamps();});
 Schema::create('creator_profiles',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->string('display_name');$t->string('slug')->unique();$t->text('bio');$t->string('speciality')->nullable();$t->string('status')->default('pending');$t->string('social_url')->nullable();$t->timestamps();});
 Schema::table('blogs',function(Blueprint $t){$t->foreignId('creator_profile_id')->nullable()->after('id')->constrained()->nullOnDelete();$t->string('review_status')->default('approved');});
}public function down():void{Schema::table('blogs',fn(Blueprint $t)=>$t->dropConstrainedForeignId('creator_profile_id'));Schema::dropIfExists('creator_profiles');Schema::dropIfExists('match_stories');Schema::dropIfExists('user_badges');Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['username','country_code','city','war_faction','bio','matchday_points','current_streak','best_streak','last_active_on']));}};
