"use client";
import {useEffect,useRef,useState} from "react";
import OnlineBattle from "./OnlineBattle";
type Unit={club:string;faction:string;trait:string;img:string;color:string};
type Move="attack"|"defend"|"counter"|"shoot";
type Side=0|1;
const actions:{id:Move;name:string;icon:string;desc:string}[]=[
 {id:"attack",name:"ATTACK",icon:"➜",desc:"Move the ball toward their goal"},
 {id:"defend",name:"TACKLE",icon:"◈",desc:"Try to win the ball back"},
 {id:"counter",name:"COUNTER",icon:"⚡",desc:"Win it and break forward"},
 {id:"shoot",name:"SHOOT",icon:"●",desc:"Take a shot at goal"}
];
const label=(m:Move)=>actions.find(a=>a.id===m)!.name;
export default function BattleGame({units,initialTeams}:{units:Unit[];initialTeams?:[number,number]}){
 const [online,setOnline]=useState(false);
 const [screen,setScreen]=useState<"mode"|"select"|"battle">(initialTeams?"battle":"mode"),[p1,setP1]=useState(initialTeams?.[0]??0),[p2,setP2]=useState(initialTeams?.[1]??1),[picker,setPicker]=useState<1|2>(1),[kickedOff,setKickedOff]=useState(false);
 const [time,setTime]=useState(60),[score,setScore]=useState<[number,number]>([0,0]),[ball,setBall]=useState(50),[possession,setPossession]=useState<Side>(0),[formation,setFormation]=useState<[number,number]>([2,2]);
 const [commentaryOn,setCommentaryOn]=useState(false),[settingsOpen,setSettingsOpen]=useState(false);
 const [phase,setPhase]=useState<"player"|"cpu"|"result">("player"),[lastMoves,setLastMoves]=useState<[Move|null,Move|null]>([null,null]),[tick,setTick]=useState(0),[log,setLog]=useState("Kick off and take the ball forward."),[goal,setGoal]=useState<string|null>(null),[event,setEvent]=useState("KICK OFF");
 const audio=useRef<AudioContext|null>(null),musicGain=useRef<GainNode|null>(null),musicTimer=useRef<number|null>(null),voiceQueue=useRef<string[]>([]),speaking=useRef(false),a=units[p1],b=units[p2],finished=time<=0,canShoot=possession===0&&ball>=76;
 useEffect(()=>{if(screen!=="battle"||!kickedOff||phase!=="player"||finished)return;const id=setInterval(()=>setTime(t=>Math.max(0,t-1)),1000);return()=>clearInterval(id)},[screen,kickedOff,phase,finished]);
 useEffect(()=>{const locked=screen==="battle"&&kickedOff&&!finished;document.body.classList.toggle("matchLocked",locked);return()=>document.body.classList.remove("matchLocked")},[screen,kickedOff,finished]);
 useEffect(()=>{if(time===0){setEvent("FULL TIME");commentate(score[0]===score[1]?`${a.club} and ${b.club} plant their banners at dusk. Neither falls; the field is shared.`:score[0]>score[1]?`The war council crowns ${a.club} high kings of this field!`:`The war council crowns ${b.club} high kings of this field.`)}},[time]);
 useEffect(()=>()=>{speechSynthesis?.cancel();if(musicTimer.current)clearInterval(musicTimer.current);audio.current?.close()},[]);
 const speakNext=()=>{if(speaking.current||!voiceQueue.current.length||typeof speechSynthesis==="undefined")return;const text=voiceQueue.current.shift()!;speaking.current=true;if(musicGain.current&&audio.current)musicGain.current.gain.setTargetAtTime(.014,audio.current.currentTime,.12);const u=new SpeechSynthesisUtterance(text),vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/Daniel|Arthur|Oliver|George|Google UK English Male/i.test(v.name))||vs.find(v=>v.lang==="en-GB")||vs.find(v=>v.lang.startsWith("en"))||null;u.rate=1.08;u.pitch=.96;u.volume=.96;u.onend=u.onerror=()=>{if(musicGain.current&&audio.current)musicGain.current.gain.setTargetAtTime(.055,audio.current.currentTime,.45);speaking.current=false;window.setTimeout(speakNext,180)};speechSynthesis.speak(u)};
 const voice=(text:string)=>{if(!commentaryOn)return;voiceQueue.current=[text];if(!speaking.current)speakNext()};
 const startMusic=()=>{try{const C=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext,c=audio.current||(audio.current=new C());c.resume();if(musicGain.current)return;const master=c.createGain();master.gain.value=.055;master.connect(c.destination);musicGain.current=master;const drone=(hz:number,type:OscillatorType,gain:number)=>{const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=hz;g.gain.value=gain;o.connect(g).connect(master);o.start()};drone(55,"sine",.14);drone(82.4,"triangle",.045);let beat=0;const drum=()=>{const now=c.currentTime+.03;for(let i=0;i<4;i++){const at=now+i*.48,o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(i===0?105:78,at);o.frequency.exponentialRampToValueAtTime(38,at+.32);g.gain.setValueAtTime(i===0?.7:.42,at);g.gain.exponentialRampToValueAtTime(.001,at+.38);o.connect(g).connect(master);o.start(at);o.stop(at+.4)}if(beat++%2===1){const o=c.createOscillator(),g=c.createGain(),at=now+1.7;o.type="sawtooth";o.frequency.value=110;g.gain.setValueAtTime(.04,at);g.gain.exponentialRampToValueAtTime(.001,at+.25);o.connect(g).connect(master);o.start(at);o.stop(at+.26)}};drum();musicTimer.current=window.setInterval(drum,1920)}catch{}};
 const fx=(kind:"kick"|"tackle"|"shot"|"goal"|"whistle")=>{try{const C=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext,c=audio.current||(audio.current=new C()),now=c.currentTime;const tone=(f:number,d:number,at=0,gain=.08)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(f,now+at);o.frequency.exponentialRampToValueAtTime(Math.max(40,f/2),now+at+d);g.gain.setValueAtTime(gain,now+at);g.gain.exponentialRampToValueAtTime(.001,now+at+d);o.connect(g).connect(c.destination);o.start(now+at);o.stop(now+at+d)};c.resume();if(kind==="kick")tone(105,.15);if(kind==="tackle"){tone(180,.08);tone(90,.17,.06)}if(kind==="shot")tone(140,.3,0,.13);if(kind==="goal")[0,.12,.24,.36].forEach((x,i)=>tone(180+i*55,.45,x,.12));if(kind==="whistle"){tone(1100,.3);tone(1250,.35,.35)}}catch{}};
 const commentate=(text:string)=>{setLog(text);voice(text)};
 const reset=()=>{speechSynthesis?.cancel();voiceQueue.current=[];speaking.current=false;setTime(60);setScore([0,0]);setBall(50);setPossession(0);setFormation([2,2]);setPhase("player");setLastMoves([null,null]);setTick(0);setGoal(null);setEvent("KICK OFF");setKickedOff(false);setLog("Kick off and take the ball forward.")};
 const trackGrowth=(event:"joined"|"completed")=>{const ref=sessionStorage.getItem("matchday_ref");if(!ref)return;const fixtureId=new URLSearchParams(location.search).get("fixture");void fetch("/war/api/growth/referral",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:ref,fixtureId:fixtureId?Number(fixtureId):null,source:"challenge",event})})};
 const select=(i:number)=>{if(picker===1){setP1(i);setPicker(2)}else{setP2(i===p1?(i+1)%units.length:i);reset();setScreen("battle")}};
 const flashGoal=(side:Side)=>{setScore(s=>side===0?[s[0]+1,s[1]]:[s[0],s[1]+1]);setGoal(`${side===0?a.club:b.club} SCORE!`);setEvent("GOAL");fx("goal");commentate(`Goal for ${side===0?a.club:b.club}! The raid lands... the line is breached... and ${side===0?b.club:a.club}'s banner falls.`);setTimeout(()=>{setGoal(null);setBall(50);setPossession(side===0?1:0);setFormation([2,2])},2200)};
 const cpuTurn=(playerMove:Move)=>{setPhase("cpu");setEvent(`${b.club} MOVE`);let move:Move;if(possession===1&&ball<=24)move="shoot";else if(possession===1)move="attack";else move=Math.random()<.62?"defend":"counter";setLastMoves([playerMove,move]);setTick(t=>t+1);commentate(move==="shoot"?`${b.club} are lining up the shot...`:move==="attack"?`${b.club} come forward now, banner raised.`:`${b.club} close ranks... and hunt for the ball.`);fx(move==="shoot"?"shot":move==="attack"?"kick":"tackle");setTimeout(()=>resolveCpu(move),900)};
 const resolveCpu=(move:Move)=>{if(move==="shoot"){if(Math.random()<.4){flashGoal(1)}else{setPossession(0);setBall(24);commentate(`${a.club}'s fortress holds! The strike is turned aside.`);setEvent("SAVED")}}else if(move==="attack"&&possession===1){setBall(x=>Math.max(12,x-14));setFormation(f=>[f[0],Math.min(6,f[1]+1)]);commentate(`${b.club} gain ground. ${a.club}'s gate draws near.`)}else if((move==="defend"||move==="counter")&&possession===0){if(Math.random()<.42){setPossession(1);setBall(x=>Math.max(10,x-(move==="counter"?12:3)));commentate(`${b.club} capture the banner and turn the tide!`)}else commentate(`${a.club} hold firm and keep the banner.`)}setPhase("result");setTimeout(()=>{setPhase("player");setEvent(`${a.club} TURN`)},520)};
 const play=(move:Move)=>{if(phase!=="player"||finished)return;if(move==="shoot"&&!canShoot)return;setEvent(`${a.club} MOVE`);setLastMoves([move,null]);setTick(t=>t+1);if(move==="attack"){if(possession===0){setBall(x=>Math.min(88,x+14));setFormation(f=>[Math.min(6,f[0]+1),f[1]]);commentate(`${a.club} charge beneath the raised banner and gain ground toward ${b.club}'s gate!`);fx("kick")}else{commentate(`${b.club} hold the banner. ${a.club} must close ranks and win it back.`);fx("tackle")}}if(move==="defend"||move==="counter"){if(possession===1){const won=Math.random()<(move==="counter"?.58:.72);fx("tackle");if(won){setPossession(0);setBall(x=>Math.min(90,x+(move==="counter"?12:3)));setFormation(f=>[Math.min(6,f[0]+(move==="counter"?1:0)),Math.max(0,f[1]-1)]);commentate(move==="counter"?`${a.club} rally, seize the banner, and turn the tide!`:`${a.club}'s shield wall closes. ${b.club} are driven back!`)}else commentate(`${a.club}'s shield wall breaks. ${b.club} keep the banner.`)}else commentate(`${a.club} already have the banner. Sound the charge!`)}if(move==="shoot"){fx("shot");commentate(`${a.club} hurl a strike at ${b.club}'s fortress!`);setTimeout(()=>{if(Math.random()<.52)flashGoal(0);else{setPossession(1);setBall(76);commentate(`${b.club}'s gate holds! The strike is beaten away and they claim the banner.`);setEvent("SAVED")}},650);setTimeout(()=>cpuTurn(move),1800);return}setTimeout(()=>cpuTurn(move),1100)};
 const unit=(side:Side,i:number)=>{const attacker=i<3,base=side===0?16:84,adv=(attacker?formation[side]*4.5:formation[side]*2)*(side===0?1:-1),lane=attacker?[27,50,73][i]:[39,61][i-3];return <div key={`${side}-${i}-${tick}`} className={`fieldAvatar side${side} ${attacker?"attacker":"defender"} ${lastMoves[side]||""}`} style={{left:`${base+adv}%`,top:`${lane}%`,borderColor:side===0?a.color:b.color}}><img src={`/war/warriors/${side===0?a.img:b.img}`} alt=""/><b>{attacker?"A":"D"}{attacker?i+1:i-2}</b></div>};
 if(online)return <OnlineBattle units={units} onClose={()=>setOnline(false)}/>;
 if(screen==="mode")return <div className="gameShell gameStart"><button className="gameSettingsButton" onClick={()=>setSettingsOpen(x=>!x)} aria-expanded={settingsOpen}>⚙ Settings</button>{settingsOpen&&<div className="gameSettings"><b>GAME AUDIO</b><label><span><strong>Audio commentary</strong><small>Spoken commentary during play</small></span><input type="checkbox" checked={commentaryOn} onChange={e=>{setCommentaryOn(e.target.checked);if(!e.target.checked){speechSynthesis?.cancel();voiceQueue.current=[];speaking.current=false}}}/></label></div>}<p className="eyebrow">THE WAR ROOM</p><h2>Play the 60-second match.</h2><p>Move the ball, win it back and shoot when you reach the goal.</p><div className="modeCards"><button onClick={()=>{setPicker(1);setScreen("select")}}><i>▶</i><b>Play CPU</b><span>Single-player football battle</span></button><button onClick={()=>setOnline(true)}><i>Ⅱ</i><b>Two Players</b><span>Play online with a room code</span></button></div></div>;
 if(screen==="select")return <div className="gameShell selectScreen"><button className="backButton" onClick={()=>picker===2?setPicker(1):setScreen("mode")}>← Back</button><p className="eyebrow">{picker===1?"CHOOSE YOUR TEAM":"CHOOSE THE CPU"}</p><h2>{picker===1?"Who will you command?":"Who will you face?"}</h2><div className="roster">{units.map((u,i)=><button key={u.club} className={picker===2&&i===p1?"chosen":""} onClick={()=>select(i)} disabled={picker===2&&i===p1}><img src={`/war/warriors/${u.img}`} alt={u.faction}/><span style={{background:u.color}}/><div><small>{u.club}</small><b>{u.faction}</b></div></button>)}</div></div>;
 if(!kickedOff)return <div className="gameShell kickoff"><button className="backButton" onClick={()=>setScreen("select")}>← Change teams</button><div className="kickoffCommanders"><img src={`/war/warriors/${a.img}`} alt=""/><div><small>READY TO PLAY</small><h2>{a.club}<i>VS</i>{b.club}</h2><p>Attack moves the banner. Tackle reclaims it. Strike when you reach the fortress.</p><button onClick={()=>{trackGrowth("joined");startMusic();setKickedOff(true);setEvent(`${a.club} TURN`);commentate(`The horns sound! ${a.club} and ${b.club} plant their banners. The campaign begins.`);fx("whistle")}}>KICK OFF</button></div><img src={`/war/warriors/${b.img}`} alt=""/></div></div>;
 const result=score[0]===score[1]?"DRAW":score[0]>score[1]?`${a.club} WIN!`:`${b.club} WIN!`;
 return <div className="gameShell battleScreen">{goal&&<div className={`goalFlash ${goal.startsWith(a.club)?"yourGoal":"enemyGoal"}`}><small>{time}&apos;</small><b>{goal}</b><span>{score[0]} — {score[1]}</span></div>}<div className="gameTop"><button className="backButton" onClick={()=>{reset();setScreen("mode")}}>← Exit</button><div className="matchClock"><small>{event}</small><b>{time}&apos;</b></div><p>{a.club} VS {b.club}</p></div><div className="scoreboard"><span>{a.club}</span><b>{score[0]} — {score[1]}</b><span>{b.club}</span></div><div className={`turnBanner phase-${phase}`}><i>{phase==="player"?a.club:b.club}</i><div><small>{phase==="player"?`${a.club} TURN`:`WATCH ${b.club}`}</small><b>{phase==="player"?(possession===0?`${a.club} HOLD THE BANNER`:`RECLAIM THE BANNER FROM ${b.club}`):log}</b></div></div><div className="battleStage formationField ballField"><img className="commanderBg commanderLeft" src={`/war/warriors/${a.img}`} alt=""/><img className="commanderBg commanderRight" src={`/war/warriors/${b.img}`} alt=""/><div className="fieldLines"><i/><i/><b/></div>{[0,1,2,3,4].map(i=>unit(0,i))}{[0,1,2,3,4].map(i=>unit(1,i))}<div className={`matchBall owner${possession}`} style={{left:`${ball}%`}}><b>●</b><span>{possession===0?`${a.club} BANNER`:`${b.club} BANNER`}</span></div><div className="goalMouth yourNet">{a.club} FORTRESS</div><div className="goalMouth cpuNet">{b.club} FORTRESS</div></div><div className="commentaryBox"><small>MYTH COMMENTARY · LIVE WAR DRUMS</small><p>{log}</p></div>{finished?<div className="victoryActions"><b>{result}</b><button onClick={()=>{trackGrowth("completed");reset()}}>Play again</button></div>:<div className={`footballControls ${phase!=="player"?"waiting":""}`}><h3>{phase==="player"?`${a.club}: CHOOSE AN ORDER`:`${b.club} ARE MOVING…`}</h3><div>{actions.map(x=>{const disabled=phase!=="player"||(x.id==="shoot"&&!canShoot);const recommended=phase==="player"&&(possession===0?(canShoot?x.id==="shoot":x.id==="attack"):x.id==="defend");return <button key={x.id} disabled={disabled} onClick={()=>play(x.id)} className={`${x.id} ${recommended?"recommended":""}`}><i>{x.icon}</i><b>{x.name}</b><small>{x.id==="shoot"&&!canShoot?"Reach the fortress to unlock":x.desc}</small>{recommended&&<em>TAP ME</em>}</button>})}</div></div>}</div>;
}
