"use client";
import {useEffect,useRef,useState} from "react";
type Unit={club:string;faction:string;trait:string;img:string;color:string};
type Game={status:string;ball:number;possession:number;score:[number,number];turn:number;remaining:number;endsAt?:number;event:string};
const moves=[['attack','➜','ATTACK'],['defend','◈','TACKLE'],['counter','⚡','COUNTER'],['shoot','●','SHOOT']] as const;
const playerId=()=>{const bytes=new Uint8Array(16);if(globalThis.crypto?.getRandomValues)globalThis.crypto.getRandomValues(bytes);else for(let i=0;i<bytes.length;i++)bytes[i]=Math.floor(Math.random()*256);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`};
export default function OnlineBattle({units,onClose}:{units:Unit[];onClose:()=>void}){
 const id=useRef(playerId()),[view,setView]=useState<'lobby'|'team'|'room'>('lobby'),[role,setRole]=useState<'host'|'join'>('host'),[team,setTeam]=useState(0),[room,setRoom]=useState(''),[side,setSide]=useState(0),[remote,setRemote]=useState<{hostTeam:number;guestTeam:number;connected:boolean;state:Game}|null>(null),[error,setError]=useState('');
 const call=async(path:string,body?:unknown)=>{const r=await fetch(path,{method:body?'POST':'GET',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'Connection failed');return data};
 const host=async()=>{try{const x=await call('/war/api/rooms',{playerId:id.current,team});setRoom(x.code);setSide(0);setView('room')}catch(e){setError((e as Error).message)}};
 const join=async()=>{try{const x=await call(`/war/api/rooms/${room}/join`,{playerId:id.current,team});setSide(1);setView('room')}catch(e){setError((e as Error).message)}};
 useEffect(()=>{if(view!=='room'||!room)return;let alive=true;const poll=async()=>{try{const x=await call(`/war/api/rooms/${room}`);if(alive)setRemote(x)}catch(e){if(alive)setError((e as Error).message)}};poll();const t=setInterval(poll,700);return()=>{alive=false;clearInterval(t)}},[view,room]);
 const act=async(move:string)=>{try{setError('');const state=await call(`/war/api/rooms/${room}/action`,{playerId:id.current,move});setRemote(r=>r?{...r,state}:r)}catch(e){setError((e as Error).message)}};
 if(view==='lobby')return <div className="onlineLobby"><button className="backButton" onClick={onClose}>← Back</button><p className="eyebrow">TWO PLAYER ONLINE</p><h2>Share the battlefield.</h2><p>Create a room on one phone. Enter its six-character code on the other.</p><div className="onlineChoices"><button onClick={()=>{setRole('host');setView('team')}}><b>Create room</b><span>Choose a team and invite a rival</span></button><button onClick={()=>{setRole('join');setView('team')}}><b>Join room</b><span>Enter the host’s room code</span></button></div></div>;
 if(view==='team')return <div className="onlineLobby"><button className="backButton" onClick={()=>setView('lobby')}>← Back</button><p className="eyebrow">CHOOSE YOUR TEAM</p><div className="onlineTeams">{units.map((u,i)=><button key={u.club} className={team===i?'selected':''} onClick={()=>setTeam(i)}><img src={`/war/warriors/${u.img}`} alt=""/><b>{u.club}</b></button>)}</div>{role==='host'?<button className="roomAction" onClick={host}>CREATE ROOM</button>:<div className="joinCode"><input value={room} onChange={e=>setRoom(e.target.value.toUpperCase().slice(0,6))} placeholder="ROOM CODE"/><button onClick={join} disabled={room.length!==6}>JOIN</button></div>}{error&&<p className="roomError">{error}</p>}</div>;
 const game=remote?.state,home=units[remote?.hostTeam??team],away=units[remote?.guestTeam??team],myTurn=game?.turn===side;
 const squad=(which:0|1,u:Unit)=>{const pressure=((game?.ball??50)-50)/5,shift=which===0?Math.max(-3,Math.min(10,pressure)):Math.max(-10,Math.min(3,pressure));return [0,1,2,3,4].map((n)=><div key={`${which}-${n}`} className={`onlinePlayer p${which} ${n<3?'forward':'back'} ${game?.turn===which?'moving':''}`} style={{left:`${(which===0?(n<3?28:16):(n<3?72:84))+shift}%`,top:`${[25,50,75,38,63][n]}%`,borderColor:u.color}}><img src={`/war/warriors/${u.img}`} alt=""/><b>{n<3?'A':'D'}{n<3?n+1:n-2}</b></div>)};
 const hasBall=game?.possession===side,shootingRange=!!game&&hasBall&&(side===0?game.ball>=76:game.ball<=24),moveAllowed=(move:string)=>move==="attack"?hasBall:move==="shoot"?shootingRange:!hasBall;
 return <div className="onlineMatch"><button className="backButton" onClick={onClose}>← Leave room</button><div className="roomCode"><small>ROOM CODE</small><b>{room}</b><span>{!remote?.connected?'Waiting for player two — share this code':game?.status==='ready'?'PLAYER TWO CONNECTED · HOST MUST KICK OFF':'LIVE MATCH'}</span></div>{game?.status==='ready'&&side===0&&<button className="roomAction" onClick={async()=>{const state=await call(`/war/api/rooms/${room}/start`,{playerId:id.current});setRemote(r=>r?{...r,state}:r)}}>KICK OFF</button>}{(!game||game.status==='waiting'||game.status==='ready')?<div className="waitingRoom"><div><img src={`/war/warriors/${home.img}`} alt=""/><b>PLAYER 1 · {home.club}</b></div><i>VS</i><div>{remote?.connected?<><img src={`/war/warriors/${away.img}`} alt=""/><b>PLAYER 2 · {away.club}</b></>:<span className="awaitingPlayer">PLAYER 2<br/>WAITING TO JOIN</span>}</div></div>:<><div className="onlineScore"><span>{home.club}</span><b>{game.score[0]} — {game.score[1]}</b><span>{away.club}</span></div><div className="onlineField">{squad(0,home)}{squad(1,away)}<div className={`onlineBall owner${game.possession}`} style={{left:`${game.ball}%`}}>●</div><span className="net left">GOAL</span><span className="net right">GOAL</span></div><div className={`onlineEvent ${myTurn?'yourTurn':''}`}><small>{game.remaining} SECONDS · {myTurn?'YOUR TURN — CHOOSE AN ORDER':`WAITING FOR ${side===0?away.club:home.club}`}</small><b>{game.event}</b></div>{game.status==='finished'?<div className="onlineResult">FULL TIME · {game.score[0]===game.score[1]?'DRAW':game.score[0]>game.score[1]?`${home.club} WIN`:`${away.club} WIN`}</div>:<div className={`onlineControls ${myTurn?'':'disabled'}`}>{moves.map(m=>{const shoot=m[0]==='shoot',canShoot=game.possession===side&&(side===0?game.ball>=76:game.ball<=24);return <button key={m[0]} disabled={!myTurn||!moveAllowed(m[0])} onClick={()=>act(m[0])}><i>{m[1]}</i><b>{m[2]}</b>{shoot&&!canShoot&&<small>Move closer first</small>}</button>})}</div>}</>}{error&&<p className="roomError">{error}</p>}</div>
}
