"use client";
import React,{useEffect,useRef,useState} from "react";
import BattleGame from "./BattleGame";
import AudienceCapture from "./AudienceCapture";

type Warrior={club:string;faction:string;trait:string;img:string;color:string};
const W:Warrior[]=[
 {club:"Arsenal",faction:"Roman Legion",trait:"Disciplined · Methodical",img:"arsenal.png",color:"#e30613"},{club:"Aston Villa",faction:"Anglo-Saxon Housecarls",trait:"Sturdy · Defensive",img:"aston-villa.png",color:"#95bfe5"},{club:"Bournemouth",faction:"Barbary Corsairs",trait:"Fast · Opportunistic",img:"bournemouth.png",color:"#da291c"},{club:"Brentford",faction:"Prussian Line Infantry",trait:"Efficient · Drilled",img:"brentford.png",color:"#e30613"},{club:"Brighton",faction:"Byzantine Cataphracts",trait:"Technical · Elegant",img:"brighton.png",color:"#0057b8"},{club:"Chelsea",faction:"Ottoman Janissaries",trait:"Elite · Disciplined",img:"chelsea.png",color:"#034694"},{club:"Coventry City",faction:"Zulu Impi",trait:"Disciplined · Fearless",img:"coventry.png",color:"#69b3e7"},{club:"Crystal Palace",faction:"Saxon Fyrd",trait:"Scrappy · Resilient",img:"crystal-palace.png",color:"#1b458f"},{club:"Everton",faction:"Norman Knights",trait:"Old-guard · Stubborn",img:"everton.png",color:"#3a64b7"},{club:"Fulham",faction:"Venetian Marines",trait:"Composed · Understated",img:"fulham.png",color:"#ddd"},{club:"Hull City",faction:"Numidian Cavalry",trait:"Swift · Unpredictable",img:"hull.png",color:"#f5a12d"},{club:"Ipswich Town",faction:"Rus’ Varangian Guard",trait:"Loyal · Steadfast",img:"ipswich.png",color:"#3a64b7"},{club:"Leeds United",faction:"White Rose Yorkist Army",trait:"Proud · Resurgent",img:"leeds.png",color:"#ffcd00"},{club:"Liverpool",faction:"Norse Vikings",trait:"Ferocious · Relentless",img:"liverpool.png",color:"#c8102e"},{club:"Manchester City",faction:"Mongol Horde",trait:"Overwhelming · Fast",img:"manchester-city.png",color:"#6cabdd"},{club:"Manchester United",faction:"Napoleonic Grenadiers",trait:"Historic · Powerful",img:"manchester-united.png",color:"#da291c"},{club:"Newcastle United",faction:"Norse-Northumbrian Raiders",trait:"Passionate · Raiding",img:"newcastle.png",color:"#ddd"},{club:"Nottingham Forest",faction:"Robin Hood’s Outlaws",trait:"Guerrilla · Cunning",img:"nottingham-forest.png",color:"#dd0000"},{club:"Sunderland",faction:"Northern Rebel Clans",trait:"Underdog · Gritty",img:"sunderland.png",color:"#eb172b"},{club:"Tottenham Hotspur",faction:"Spartan Hoplites",trait:"Proud · Historic · Brittle",img:"tottenham.png",color:"#ddd"}];
const get=(club:string)=>W.find(w=>w.club===club)!;
const fallbackMatches=[["Arsenal","Coventry City","FRI 21 AUG · 20:00"],["Hull City","Manchester United","SAT 22 AUG · 12:30"],["Everton","Crystal Palace","SAT 22 AUG · 15:00"],["Ipswich Town","Sunderland","SAT 22 AUG · 15:00"],["Nottingham Forest","Leeds United","SAT 22 AUG · 15:00"],["Brentford","Tottenham Hotspur","SAT 22 AUG · 17:30"],["Brighton","Aston Villa","SUN 23 AUG · 14:00"],["Manchester City","Bournemouth","SUN 23 AUG · 14:00"],["Newcastle United","Liverpool","SUN 23 AUG · 16:30"],["Fulham","Chelsea","MON 24 AUG · 20:00"]];
const clubName=(name:string)=>({"Brighton & Hove Albion":"Brighton","AFC Bournemouth":"Bournemouth","Manchester City FC":"Manchester City","Manchester United FC":"Manchester United","Newcastle United FC":"Newcastle United","Nottingham Forest FC":"Nottingham Forest","Tottenham Hotspur FC":"Tottenham Hotspur","West Ham United FC":"West Ham United","Wolverhampton Wanderers FC":"Wolverhampton Wanderers"}[name]||name.replace(/ FC$/,""));
const grammar=[["Goal","A raid lands — warriors breach the line, steal plunder or a banner"],["Assist","A flank manoeuvre — one warrior draws the shield wall, opening the gap"],["Red card","The warrior is captured and dragged from the field in chains"],["Yellow card","The warrior is struck down, wounded, then rises again"],["Penalty scored","A siege tower breaches the gate"],["Penalty missed","The gate holds; the siege tower collapses"],["Missed big chance","A spear is thrown and sails wide of the mark"],["Comeback","The retreating army rallies and turns the tide"],["Draw","Both banners are planted; neither falls — the field is shared at dusk"],["Clean sheet","The fortress wall holds, unbreached"],["Late winner (85’+)","A final charge as the sun sets — the last arrow finds its mark"],["Manager farewell","The old chieftain lays down his sword and passes the war-banner on"],["Trophy won","The war-council crowns a new high king; a great feast beneath the banner"],["Relegation","The army is cast out from the great council, banished to lesser lands"],["Survival","The army barely holds its gates against winter and lives to fight again"],["Hat-trick","A warrior fells three of the enemy in one day — bards will sing of it"],["Own goal","A warrior’s own blade turns against his shield-brother by cruel accident"]];
export default function WarApp(){const [card,setCard]=useState(0),[match,setMatch]=useState(0),[fixtures,setFixtures]=useState(fallbackMatches),touch=useRef(0);const step=(n:number)=>setCard(c=>(c+n+W.length)%W.length);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="ArrowRight")step(1);if(e.key==="ArrowLeft")step(-1)};addEventListener("keydown",key);fetch("/war/api/fixtures").then(r=>r.ok?r.json():Promise.reject()).then((rows:Array<{home:string;away:string;kickoff:string}>)=>{const live=rows.map(x=>{const home=clubName(x.home),away=clubName(x.away),when=new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"Europe/London"}).format(new Date(x.kickoff)).toUpperCase();return [home,away,when]}).filter(x=>get(x[0])&&get(x[1]));if(live.length){setFixtures(live);setMatch(0)}}).catch(()=>{});return()=>removeEventListener("keydown",key)},[]);const w=W[card],f=fixtures[match]||fixtures[0],home=get(f[0]),away=get(f[1]);return <main>
 <nav><a className="brand" href="#top"><span>MD</span>MATCHDAY</a><a className="backHome" href="/">← Back to Matchday</a><div><a href="#top">Film</a><a href="#armies">Armies</a><a href="#game">Play</a><a href="/shop">Shop</a><a href="#matchweek">Matchweek</a></div><details className="mobileMenu"><summary aria-label="Open menu">☰</summary><div><a href="/">← Back to Matchday</a><a href="#top">Campaign film</a><a href="#armies">Swipe the ranks</a><a href="#game">Play game</a><a href="/shop">Claim your warrior</a></div></details><b>2026/27</b></nav>
 <section id="top" className="trailer"><div><p className="eyebrow">01 · THE CAMPAIGN FILM</p><h2>Watch the<br/>armies muster.</h2><p>Twenty warriors. One throne. The campaign begins here.</p></div><video controls playsInline preload="metadata" poster="/war/warriors/arsenal.png"><source src="/war/matchday-warriors-trailer.mp4" type="video/mp4"/>Your browser does not support embedded video.</video></section>
 <section id="armies" className="deckSection"><div className="heading"><p className="eyebrow">THE TWENTY ARMIES</p><h2>Swipe the ranks.</h2><span>{String(card+1).padStart(2,"0")} / 20</span></div><div className="deck" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-touch.current;if(Math.abs(d)>45)step(d<0?1:-1)}}>
  <button className="arrow prev" onClick={()=>step(-1)} aria-label="Previous army">←</button><article style={{"--accent":w.color} as React.CSSProperties}><img src={`/war/warriors/${w.img}`} alt={`${w.club} as ${w.faction}`}/><div className="cardText"><small>{w.club}</small><h2>{w.faction}</h2><p>{w.trait}</p></div></article><button className="arrow next" onClick={()=>step(1)} aria-label="Next army">→</button>
 </div><div className="dots">{W.map((x,i)=><button key={x.club} className={i===card?"active":""} onClick={()=>setCard(i)} aria-label={`View ${x.club}`}/>)}</div><p className="hint">← SWIPE OR USE ARROW KEYS →</p><a className="wallpaperJump" href="/shop">Claim your warrior in the shop →</a></section>
 <section id="game" className="gameSection"><BattleGame units={W}/></section>
 <section id="matchweek" className="matchweek"><div className="heading"><p className="eyebrow">OPENING CAMPAIGN · MATCHWEEK 01</p><h2>Face the enemy.</h2><span>21—24 AUG</span></div><div className="arena"><div className="fighter left"><img src={`/war/warriors/${home.img}`} alt=""/><div><small>HOME · {home.club}</small><h3>{home.faction}</h3></div></div><div className="versus"><b>VS</b><span>{f[2]}</span></div><div className="fighter right"><img src={`/war/warriors/${away.img}`} alt=""/><div><small>AWAY · {away.club}</small><h3>{away.faction}</h3></div></div></div><div className="fixtureRail">{fixtures.map((x,i)=><button key={x[0]} className={i===match?"active":""} onClick={()=>setMatch(i)}><b>{i+1}</b><span>{x[0]}<i>v</i>{x[1]}</span></button>)}</div></section>
 <section id="grammar" className="grammar"><div className="grammarIntro"><p className="eyebrow">THE CORE LOGIC LAYER</p><h2>The Myth<br/>Grammar.</h2><p>Football is the event. Myth is how it will be remembered. This translation table turns every decisive beat into the language of raids, walls, banners and kings.</p></div><div className="rules">{grammar.map((g,i)=><article key={g[0]}><b>{String(i+1).padStart(2,"0")}</b><h3>{g[0]}</h3><p>{g[1]}</p></article>)}</div></section>
 <AudienceCapture/><footer><div className="brand"><span>MD</span>MATCHDAY</div><p>Fan-made visual mythology. AI-generated artwork.</p><a href="#top">Return to the watchtower ↑</a></footer>
 </main>}
